### ISSUE TITLE
The restriction of running this software is not clear

### ISSUE THREAD

**Issue by BlueSkyDetector** [cam-inc/viron#307]
## Overview
- What is the restriction of running this software not just as source?

I know viron itself is licensed as MIT Licence.
What I'd like to know is restrictions when I actually execute and use it.
Because viron works with some libraries, for example "highcharts".
"highcharts" is supplied only as "CC BY-NC 3.0" when we use it for free.
https://shop.highsoft.com/highcharts
When I use viron, I have to use highcharts also.
Hence, at least, I cannot use it for commercial use.

Could you make it clear which restrictions I get for using viron?

**Comment by cathcheeno** [comment]
@BlueSkyDetector We will reconsider the License and check libraries we use again. Chances are we change libraries(e.g. highchart) to keep viron under MIT License. We will let you know once it get clear.

**Comment by ejithon** [comment]
Thank you for interested our project.

As you say, it seems necessary to purchase the paid license of Highcharts to redistribute our project.

We'll do our best to resolve this problem by replacing it to another chart library as soon as possible.

Thank you for the report.

**Comment by ejithon** [comment]
@BlueSkyDetector 
Thank you for interested our project.

As you say, it seems necessary to purchase the paid license of Highcharts to redistribute our project.

We'll do our best to resolve this problem by replacing it to another chart library as soon as possible.

Thank you for the report.

**Comment by BlueSkyDetector** [comment]
@ejithon 
Thank you for the quick response.

As far as I checked "dependencies" section in package.json, I found another software "qrious" which can affect Viron license.
It's licensed under GPL3 which requires Viron to be distributed also as GPL3.

qrious: https://github.com/neocotic/qrious/blob/master/LICENSE.md

**Comment by cathcheeno** [comment]
@BlueSkyDetector We just released v1.2.0.  See PRs below for more detail.

- #308
- #309 
- #310

**Comment by BlueSkyDetector** [comment]
@cathcheeno 
Thank you.
It looks good :+1:
