### ISSUE TITLE
should display error if the status code is 200  but incorrect when add endpoint

### ISSUE THREAD

**Issue by tempakyousuke** [cam-inc/viron#311]
例えば
https://cam-inc.github.io/viron/latest/#/
で管理画面を追加する際、URLに
https://cam-inc.github.io/viron/latest/#/
を入力した時、「エンドポイントを追加しました」と表示されますが、実際には何も起きず追加されません。

自分で用意したURLがステータスコード401を返してなかったことが原因でしたが、１時間ほどこの問題ではまってしまいました。
ステータスコードが200の場合、実際には追加できてなくても「エンドポイントを追加しました」と出てしまうようなので、エラーが表示されるようにしていただけたらと思います。

**Comment by cathcheeno** [comment]
@tempakyousuke 手元の環境で再現出来ました、順次対応しますね 👍
