### ISSUE TITLE
Try add CRUD as shown in documents, but have an error when I change swagger.yaml file

### ISSUE THREAD

**Issue by Irina-13** [cam-inc/viron#312]
## Overview (Required)
When I changed swagger.yaml file as shown in this document: https://cam-inc.github.io/viron-doc/docs/dev_crud.html
(I tried to add new CRUD)

My viron_api_1 container stop working, it's showing this error:

{ Error: Swagger validation errors:
    at /demo/node_modules/swagger-node-runner/index.js:210:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  validationErrors: 
   [ { code: 'INVALID_TYPE',
       params: [Array],
       message: 'Expected type object but found type string',
       path: [Array],
       schemaId: 'http://swagger.io/v2/schema.json#' },
     { code: 'INVALID_TYPE',
       params: [Array],
       message: 'Expected type object but found type string',
       path: [Array],
       schemaId: 'http://swagger.io/v2/schema.json#' },
     { code: 'ONE_OF_MISSING',
       params: [],
       message: 'Not a valid response definition',
       path: [Array],
       schemaId: 'http://swagger.io/v2/schema.json#',
       inner: [Array] },
     { code: 'INVALID_TYPE',
       params: [Array],
       message: 'Expected type object but found type string',
       path: [Array],
       schemaId: 'http://swagger.io/v2/schema.json#' },
     { code: 'ONE_OF_MISSING',
       params: [],
       message: 'Not a valid response definition',
       path: [Array],
       schemaId: 'http://swagger.io/v2/schema.json#',
       inner: [Array] },
     { code: 'ONE_OF_MISSING',
       params: [],
       message: 'Not a valid response definition',
       path: [Array],
       schemaId: 'http://swagger.io/v2/schema.json#',
       inner: [Array] } ] }
[nodemon] app crashed - waiting for file changes before starting...

Can you help me to fix it, please?

**Comment by noritama** [comment]
@Irina-13 
It looks like `swagger.yaml` validation failure.
Try go to [swagger-editor](https://editor.swagger.io/), and check the validation.

**Comment by Irina-13** [comment]
@noritama Thank you very much! It works!
It looks like it was an error in documentation sample file, but someone fixed code in documentation today or yesterday, so now it's good :)

Thank you very much for your help!!
