### ISSUE TITLE
Table component filter bug

### ISSUE THREAD

**Issue by yudppp** [cam-inc/viron#318]
## Overview (Required)

- I use [latest](https://cam-inc.github.io/viron/latest/) version
- I use table component and pagination

1.  current page is 2 page
2. I searched by name(Exist reliably)
3. But search result is not found.

I think `offset` has not been reset

## Links
- https://cam-inc.github.io/viron/latest/

## Screenshot

<img width="962" alt="2018-02-07 20 20 03" src="https://user-images.githubusercontent.com/4619802/35913997-06bf4492-0c45-11e8-83b5-283df9d763e8.png">
<img width="989" alt="2018-02-07 20 20 12" src="https://user-images.githubusercontent.com/4619802/35914001-08701e4c-0c45-11e8-8a97-b41c87f8b816.png">

**Comment by cathcheeno** [comment]
@yudppp 
I tried and could reproduce the bug you pointed out.

> I think offset has not been reset

You are right, I will change the behavior so to reset parameters related to pagination when search queries are updated.

 The fix will be on next version of Viron.
