### ISSUE TITLE
Add search function for Chart component just like table component.

### ISSUE THREAD

**Issue by 32ka** [cam-inc/viron#327]
## Overview (Required)
- TableComponent と同様に、Chart Component でも、swagger にパラメータを設定した際に 検索アイコンが表示されるようにしてほしいです。

## Links
-

## Screenshot
-

**Comment by fkei** [comment]
ダッシュボードは複数のページを表示することができます。

### 例
**左パネル**

- ダッシュボード
  - クイックスタート
  - AAAA <- 追加可能
  - BBBB <- 追加可能
