### ISSUE TITLE
WYSIWYGプレビューの表示形式

### ISSUE THREAD

**Issue by sims0728** [cam-inc/viron#335]
## Overview (Required)
- [SP/PC] WYSIWYGのプレビューでスクロールができない。
- [SP/PC] 画像の表示サイズが画面をはみ出してしまうためプレビュー内で画像の横幅を納めたい

## Links
-

## Screenshot
-

**Comment by cathcheeno** [comment]
@sims0728 再現方法を前回みたいに動画でもらえると助かりますw
