### ISSUE TITLE
Displaying image

### ISSUE THREAD

**Issue by keitatata** [cam-inc/viron#570]
**Is your feature request related to a problem? Please describe.**
Even if the element is an image url, it will be displayed as a string.

**Describe the solution you'd like**
If the element is the url string of an image, I'd like it to display the image itself instead of displaying it as a string.

**Describe alternatives you've considered**

**Additional context**
I want to display the image as in v1.
<img width="849" alt="スクリーンショット 2022-02-22 12 29 15" src="https://user-images.githubusercontent.com/45387533/155057915-b9256342-8ccb-4163-90e6-d2cb3d3be8d8.png">

**Comment by cathcheeno** [comment]
@keitatata 
Viron can't detect whether certain data is a URI string or a plain one.
I've [supported](https://github.com/cam-inc/viron/pull/584) a new format value for `Schema Objects` to give Viron more specific information: `uri-image`. Please use the `format` property with its value `uri-image` to display data in a table cell with the `<img />` HTML element.

like this:
```json
"thumb": {
  "type": "string",
  "format": "uri-image"
}
```

NOTE: currently effective only on the [development](https://discovery.viron.plus/docs/Advanced-Guides/url#url-types) environment.
