### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by keitatata** [cam-inc/viron#571]
**Is your feature request related to a problem? Please describe.**
It is difficult to check the data one by one because only a list is displayed.

**Describe the solution you'd like**
When I click on an element in the list, I would like to see a preview of it.

**Describe alternatives you've considered**

**Additional context**

**Comment by cathcheeno** [comment]
@keitatata 
Viron can't detect whether certain data is a URI string or a plain one.
I've [supported](https://github.com/cam-inc/viron/pull/584) a new format value for `Schema Objects` to give Viron more specific information: `uri-image`. Please use the `format` property with its value `uri-image` to display data in a table cell with the `<img />` HTML element.

like this:
```json
"thumb": {
  "type": "string",
  "format": "uri-image"
}
```

NOTE: currently effective only on the [development](https://discovery.viron.plus/docs/Advanced-Guides/url#url-types) environment.

**Comment by nonoakij** [comment]
The following changes seem to have resolved this issue.
https://github.com/cam-inc/viron/pull/744
