### ISSUE TITLE
Cannot convert public endpoint to private(email authentication)

### ISSUE THREAD

**Issue by danielbatch** [cam-inc/viron#606]
**Describe the bug**
Public endpoint `https://rails-oas-sample.herokuapp.com/oas` can not be converted to private, by authentication type `email`.
Though I coded following this [doc](https://discovery.viron.plus/docs/Advanced-Guides/authentication), email button does not be displayed. (attached screenshot)
Anything else other than the doc is needed?

**Expected behavior**
Email button appears.

**Screenshots**
now
![now](https://user-images.githubusercontent.com/104686031/167383639-1324e387-e439-4560-9a29-de6d367d164e.jpg)
ideal
![ideal](https://user-images.githubusercontent.com/104686031/167384281-570b759c-4760-41e5-a947-40a62735d07d.jpg)

**Additional context**
- The response header of GET `/oas`
```
X-Viron-Authtypes-Path:  /authentication
```

- The response body of GET` /authentication`
```
  {
      "list": [
        {
          "provider": "viron",
          "type": "email",
          "operationId": "signinEmail"
        }
      ],
      "oas": {
        "openapi": "3.0.2",
        "info": {
          "title": "Authentication",
          "version": "1.0.0",
          "x-pages": []
        },
        "paths": {
          "/authentication": {
            "post": {
              "operationId": "signinEmail",
              "requestBody": {
                "required": true,
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "required": ["email", "password"],
                      "properties": {
                        "email": {
                          "type": "string",
                          "format": "email"
                        },
                        "password": {
                          "type": "string",
                          "format": "password"
                        }
                      }
                    }
                  }
                }
              },
              "responses":{
                "204": {
                  "description": "No Content"
                }
              }
            }
          }
        }
      }
   }
```

I have not implemented `signout` endpoint.

**Comment by cathcheeno** [comment]
@danielbatch 
It seems that your endpoint returns a OAS document with the status code of 200, and that's why Viron treats the endpoint as a public one. 
You need to first secure your endpoint with 401 status code. Please see [this section](https://discovery.viron.plus/docs/Advanced-Guides/authentication#what-viron-does) of the doc.

Thanks :)

**Comment by danielbatch** [comment]
By returning 401, the button is displayed! Thanks.
