### ISSUE TITLE
not be able to upload and download csv file throughout viron

### ISSUE THREAD

**Issue by taitasu555** [cam-inc/viron#678]
**Describe the bug**
I want to upload or download a CSV file from viron but it does not work

**To Reproduce**
1. create csv upload and download open API
2. click the upload or download button

**Screenshots**
The below pic is to upload csv file for the post method but the body is empty
<img width="844" alt="スクリーンショット 2023-07-06 10 42 07" src="https://github.com/cam-inc/viron/assets/75059685/4ca6ebfe-5dac-4ba1-93f1-01eab8cb54c6">

correct behavior is to show a binary file in the payload 
<img width="961" alt="スクリーンショット 2023-07-06 10 44 03" src="https://github.com/cam-inc/viron/assets/75059685/3c109fb7-0b9f-4e66-a38d-44c503348ae2">

**environment**
typescript
express

**Comment by h8570rg** [comment]
It can be fixed by changing the download endpoint's response header.

Add response header
```
"access-control-expose-header": "content-disposition"
```
