### ISSUE TITLE
Did you delete all the tags?

### ISSUE THREAD

**Issue by pyama86** [cam-inc/viron#810]
It looks like all the tags have been removed. Is there a reason for this?

**Comment by fkei** [comment]
We apologize for the inconvenience. We are currently considering replacing our CI/CD and had removed it at that time, but it turned out it was in use, so we have restored it.　


https://github.com/cam-inc/viron/tags

```
v0.0.2 28874e248fd5c9ca01dc042e25d323d5ae78658c
v0.0.3 cd1f312d4c035600c4bd1e1e4d7070b2d3a3e01c
v1.1.0 1123ab1ef5e7bb674f763839e4b6066980d9388d
v1.2.0 808987eee034c2abf6a07734b3ae800dc754914d
v1.3.0 2f162869843d99a6f2b03442649ced1cbe4fdd1c
v1.3.1 09f3666ab5375426a100a9f394778ea074d455e6
v1.3.2 8a4d57229961c3d9d543e608860b9b0e4c003c1d
```

**Comment by fkei** [comment]
If you encounter any issues, please feel free to reopen the issue.

**Comment by pyama86** [comment]
thakyou for your quick fix!
